# Generated by Django 3.0.2 on 2020-01-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admission',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
    ]
